// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjwWzmwIGLsafB9bIX-93gStm0iaogjP0',
    appId: '1:41842700246:web:86ad9a01a2cf2241853e77',
    messagingSenderId: '41842700246',
    projectId: 'fir-9d900',
    authDomain: 'fir-9d900.firebaseapp.com',
    databaseURL: 'https://fir-9d900-default-rtdb.firebaseio.com',
    storageBucket: 'fir-9d900.firebasestorage.app',
    measurementId: 'G-RT1PHVR6M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb531n0AVNbIein33WcfyHFJQP-eEMzgg',
    appId: '1:41842700246:android:6d2f751738ff170a853e77',
    messagingSenderId: '41842700246',
    projectId: 'fir-9d900',
    databaseURL: 'https://fir-9d900-default-rtdb.firebaseio.com',
    storageBucket: 'fir-9d900.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfZWifUJAl3zxYw26DUA2Rj77Hn82AxzY',
    appId: '1:41842700246:ios:4a7e554230e791ca853e77',
    messagingSenderId: '41842700246',
    projectId: 'fir-9d900',
    databaseURL: 'https://fir-9d900-default-rtdb.firebaseio.com',
    storageBucket: 'fir-9d900.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfZWifUJAl3zxYw26DUA2Rj77Hn82AxzY',
    appId: '1:41842700246:ios:4a7e554230e791ca853e77',
    messagingSenderId: '41842700246',
    projectId: 'fir-9d900',
    databaseURL: 'https://fir-9d900-default-rtdb.firebaseio.com',
    storageBucket: 'fir-9d900.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjwWzmwIGLsafB9bIX-93gStm0iaogjP0',
    appId: '1:41842700246:web:4e5a27102016d6b5853e77',
    messagingSenderId: '41842700246',
    projectId: 'fir-9d900',
    authDomain: 'fir-9d900.firebaseapp.com',
    databaseURL: 'https://fir-9d900-default-rtdb.firebaseio.com',
    storageBucket: 'fir-9d900.firebasestorage.app',
    measurementId: 'G-Z81TVW5WL3',
  );
}
